on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint.yaml@main"

  build:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-build.yaml@9b12f11cb285b450c644e1a6b746ac89da940f25"
    secrets:
      DEPLOY_KEYS: ${{ secrets.DEPLOY_KEYS }}


  test:
    needs: ["lint", "build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@main"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"
